name: Create envfile

on:
  workflow_dispatch:


jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DEBUG: false
        envkey_APP_ID: ${{ secrets.APP_ID }}
        file_name: .env
        fail_on_empty: false
