name: Create envfile

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:


jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:

    - name: 'Create env file'
      run: |
          touch .env
          echo APP_ID=${{ secrets.APP_ID }} >> .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
          echo WEBHOOK_PROXY=${{ secrets.WEBHOOK_PROXY }} >> .env
          echo WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }} >> .env
          echo GITHUB_PAT=${{ secrets.PAT_GITHUB }} >> .env
          cat .env
    - run: cat .env
